# Skribki Wiki CI configuration.
# https://travis-ci.org/VevoxDigital/Skribki

language: node_js

# Building against NodeJS 6+
# Should work on 6.0/6.1.
# LTS (6.9.1 as of) recommended, stable (7.0.0 as of) appears to also work.
node_js:
- 'stable'
- '6.9.1'
- '6.1'
- '6.0'


# Install necessary packages before runtime
install:
- npm install

# Build only master/dev. Other branches are docs, examples, or legacy.
branches:
  only:
  - master
  - dev

# Setup compiler environment. Utilize G++ 4.8 over default compiler.
env:
  matrix:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
