// Skribki Locale File
// English (US)

lang.name   : English

page.opts.back    : Back to Page
page.opts.edit    : Edit
page.opts.history : History
page.opts.delete  : Delete

page.categories   : Categories

page.edit.header_content  : Page Content
page.edit.header_preview  : Page Preview
page.edit.preview_update  : Update Preview
page.edit.preview_fail    : No Preview Available

nav.login   : Login
nav.logout  : Logout
nav.user    : Hi there, @{user.username}
