// Skribki Locale File
// Sullang

lang.name   : Sullang

page.opts.back    : Proto ka
page.opts.edit    : sa Skrib
page.opts.history : Teri en
page.opts.delete  : Kyl

page.categories   : Gyen se

page.edit.header_content  : Skribsul
page.edit.header_preview  : Proto na Skrib
page.edit.preview_update  : Proto sa Syr
page.edit.preview_fail    : Proto en

nav.login   : Syri
nav.logout  : Syri en
nav.user    : Protosul te @{user.username}
